package util;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import util.Content;
import util.ContentExample;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thecontent
     *
     * @mbg.generated
     */
    long countByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thecontent
     *
     * @mbg.generated
     */
    int deleteByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thecontent
     *
     * @mbg.generated
     */
    int insert(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thecontent
     *
     * @mbg.generated
     */
    int insertSelective(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thecontent
     *
     * @mbg.generated
     */
    List<Content> selectByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thecontent
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thecontent
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);
}