package util;

import lombok.Data;

import java.util.Date;
@Data
public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thecontent.tid
     *
     * @mbg.generated
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thecontent.tname
     *
     * @mbg.generated
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thecontent.ttime
     *
     * @mbg.generated
     */
    private Date ttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thecontent.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thecontent.tid
     *
     * @return the value of thecontent.tid
     *
     * @mbg.generated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thecontent.tid
     *
     * @param tid the value for thecontent.tid
     *
     * @mbg.generated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thecontent.tname
     *
     * @return the value of thecontent.tname
     *
     * @mbg.generated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thecontent.tname
     *
     * @param tname the value for thecontent.tname
     *
     * @mbg.generated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thecontent.ttime
     *
     * @return the value of thecontent.ttime
     *
     * @mbg.generated
     */
    public Date getTtime() {
        return ttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thecontent.ttime
     *
     * @param ttime the value for thecontent.ttime
     *
     * @mbg.generated
     */
    public void setTtime(Date ttime) {
        this.ttime = ttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thecontent.state
     *
     * @return the value of thecontent.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thecontent.state
     *
     * @param state the value for thecontent.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}